### ISSUE TITLE
Secondary HDD not detected/Optical bay drive.

### ISSUE THREAD

**Issue by mikenzb** [kinoute/Hack-Dell-Latitude-E6430#3]
Thought I should report this issue incase anyone in the future runs into the same problem as me, fixed by enabling [Vit9696's ICH patch.](https://www.tonymacx86.com/threads/solved-disk-reports-uninitialized-when-running-on-usb-installer.249049/page-2#post-1722853)

AppleAHCIPort
Find
`40600200`

Replace
`00000000`

![IO ERROR FIX](https://user-images.githubusercontent.com/5982780/61607398-adad3580-aca2-11e9-855a-03a487a264f4.png)

**Comment by kinoute** [comment]
Thank you! I will add this to the README file.

**Comment by colanet** [comment]
Please can you help me i have dell e6430 am trying to install macos  niresh Mojave  i download it from Google the process will start at the point and it says macos could not be installed on your PC no parkages were eligible for install contact the software manufacturer for assistance
