### ISSUE TITLE
Sound Problem

### ISSUE THREAD

**Issue by Tuan9304** [kinoute/Hack-Dell-Latitude-E6430#4]
I have a little bit problem with VoodooHDA.kext. I tried to use AppleALC and it work great! That is the way to fix:

1. Download AppleALC: [https://github.com/acidanthera/AppleALC/releases](url)
2. Delete **VoodooHDA**,**AppleHDA Disabler** in Kext folder and add **AppleALC**
3. Open **config.plist** and edit it:

   - **Device**->**Audio**->Set **Inject** to **No**
   - **Boot**->**Arguments**->Set **alcid=12** (My codec is IDT92HD93BXX, you can search your alcid [here](https://github.com/acidanthera/AppleALC/wiki/Supported-codecs))

4. Save file and restart your OS. Finish!

**Comment by kinoute** [comment]
Hey,

Thanks for the tip. In my case, VoodooHDA works fine (input and output). I just have "low" volume but I'm not sure if it's related to this kext in particular. I did try AppleALC when I made this hackintosh but I couldn't make it to work OOTB. I will try your settings tomorrow at work!

Could you tell me more about the "problem" you had with VoodooHDA by the way?

**Comment by Tuan9304** [comment]
Thanks for your reply,

VoodooHDA is fine but I think AppleALC has little better sound quality (my opinion) and I also have low volume with VoodooHDA too so AppleALC is my choice.

Hope to see it work well on your "Mac"

**Comment by kinoute** [comment]
Thank you!

I just followed your instructions and get rid of VoodooHDA and the other kext. Input and output seem to still work, and I think the volume is not anymore an issue. I updated the repo. Thanks again.
