### ISSUE TITLE
Internal HDD not showing up in Disk Utility

### ISSUE THREAD

**Issue by octoturt** [kinoute/Hack-Dell-Latitude-E6430#8]
It's just not there. Not anywhere when I run `diskutil list`, either.

**Comment by octoturt** [comment]
A few minutes of testing revealed that macOS wouldn't read the drive on my actual MacBook, which means I guess it's just incompatible with macOS.

**Comment by octoturt** [comment]
Okay, I swapped it out for a hard drive that DID show up on my MacBook when plugged in, and it's still not showing up. Any ideas?

**Comment by kinoute** [comment]
Hi,

It's going to be hard to debug without any more infos. When does it not show up? At boot? In the Installer?

**Comment by octoturt** [comment]
After it's booted, in Disk Utility and at the installer. However, the solution may turn out to be to RTFM, as I forgot to set SATA Operations to AHCI. It's booting right now, and if this fixes my issue I'll go ahead and close it.

**Comment by octoturt** [comment]
I am a FOOL and a BUFFOON.
