### ISSUE TITLE
Can't get webcam to function with instructed setup. 

### ISSUE THREAD

**Issue by ehamwey** [kinoute/Hack-Dell-Latitude-E6430#9]
Hello,

My E6430 is running 10.14.6, it has a 1600x900 display, i7-3520M, 16GB of RAM and the NVS 5200m (although only using the integrated Intel GPU). I am unable to get the webcam to show in any applications in the OS. My DSDT.aml and config.plist are updated with the ones in the 6430u_1600x900 folder, otherwise my EFI folder is the same as the one here. 

Any suggestions?

**Comment by kinoute** [comment]
Hello,

I don't have this model so it's gonna be hard to help you. Does the webcam at least appear in the system infos? If you start "Photo Booth", in the menus you should have something like "Devices". Does it appear there?

What is your BIOS version? Sometimes, a too much recent BIOS can be the problem.
